// examples/vibe-distill.js — seed 3 end-to-end: a persona playtest run
// emits a CANON.md stub. The stub is GENERATED by the distiller, never
// hand-written; the receipt chain is verified before the stub is trusted.
//
//   node examples/vibe-distill.js [--check] [path-to-transcript]
//
// --check re-verifies the printed stub with verifyStub() after rendering
// (the honest loop: generate, then read the artifact back).

import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import { distill, verifyStub } from '../src/distill.js';
import { scanLedger } from '../src/core.js';

const HERE = dirname(fileURLToPath(import.meta.url));
const arg = process.argv[2];
const check = arg === '--check';
const path = join(HERE, 'fixtures', 'playest-jeviter-tui.md');
const transcript = readFileSync(path, 'utf8');

const d = distill(transcript, {
  personaSet: 'sre-oncall',
  now: new Date().toISOString(),
});

process.stdout.write(d.stub);

const gate = scanLedger(d.gate.ledger.entries);
console.error(`\n[distill] lessons: ${d.pinned.length} pinned, `
  + `${d.silences} silenced, ${d.refused.length} refused`);
console.error(`[distill] gate: ${d.admission.escalated} escalated, `
  + `${d.admission.shed} shed — ${gate.reading}`);
console.error(`[distill] main ledger verify: ${d.ledger.verify()}`);
console.error(`[distill] stub well-formed: ${d.wellFormed}`);

if (check) {
  const v = verifyStub(d.stub);
  console.error(`[distill] --check re-verify: ${v.ok ? 'PASS' : 'FAIL ' + v.problems.join('; ')}`);
  process.exit(v.ok ? 0 : 1);
}
process.exit(d.ledger.verify() && d.wellFormed ? 0 : 1);
